server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
  redis:
    # redis数据库索引(默认为0)，我们使用索引为1的数据库，避免和其他数据库冲突
    database: 1
    # redis服务器地址
    host: 127.0.0.1
    # redis端口（默认为6379）
    post: 6379
    # redis访问密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 20000

mybatis-plus:
  mapper-locations: classpath:com/mapper/xml/*Mapper.xml
  type-aliases-package: com.model.entity;
  type-enums-package: com.model.enums;
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

logging:
  level:
    com: debug

swagger:
  enable: true